camera_id: cam_01
stream_fps: 23
traffic_light_rois: []
stop_line:
- [928, 619]
- [946, 660]
restricted_zones: {}
stop_line_direction: NORTH
no_parking_zones:
  zone_1:
  - [662, 375]
  - [687, 457]
  - [804, 450]
  - [766, 353]
  - [664, 374]
speed_zones: {}
